########################################################################
# @author Serhii Nekhaienko <serhi.nekhaienko@gmail.com>
# @license MIT
# @copyright Serhii Nekhaienko &copy 2020
# @version 2.0.0
# @project endorphin-studio/browser-detector-tests
########################################################################
dataRepo: "{vendor}/endorphin-studio/browser-detector-tests-data"
configDir: "{data}/data"
testObjects:
    browser: "{config}/browser/"
    os: "{config}/os/"
    device: "{config}/device/"
    robot: "{config}/robot/"
    model: "{config}/model/"