########################################################################
# @author Serhii Nekhaienko <serhi.nekhaienko@gmail.com>
# @license MIT
# @copyright Serhii Nekhaienko &copy 2020
# @version 2.0.0
# @project endorphin-studio/browser-detector-tests
########################################################################
configDir: "%s/data/"
testObjects:
    browser: "%s/browser/"
    os: "%s/os/"
    device: "%s/device/"
    robot: "%s/robot/"
    model: "%s/model/"